## https://www.appveyor.com/docs/appveyor-yml/

image:
- Visual Studio 2022

#services:
#- docker

version: 1.1.{build}

configuration:
- Debug

platform: Any CPU

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USER: corts
  DOCKER_PASS:
    secure: 0rxw6OrmXRqB3UuBZFbC/w==
  SONAR_TOKEN:
    secure: iMwieUAbbS4oTgEVtdGWUujzaBkeNjhFzsPMj8Y3c8vkjWyCN2miKlyfWA25jtBr

install:
  - ps: $env:DOCKER_PASS | docker login --username $env:DOCKER_USER --password-stdin
  - docker version

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- appveyor-retry dotnet restore src -v Minimal
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dotnet --info

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

build_script:
- ps: >-
    $buildNumber = $env:APPVEYOR_BUILD_NUMBER;
    $branch = $env:APPVEYOR_REPO_BRANCH;
    cd shoppingcart-api;
    .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber -pushImage;

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  disable_publish_on_pr: true
